# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rMessage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xba\x05\n\x07Message\x12\'\n\x07Licence\x18\x01 \x01(\x0b\x32\x16.Message.LicenceStruct\x12!\n\x04Type\x18\x02 \x01(\x0e\x32\x13.Message.TypeStruct\x12\x0f\n\x07\x43ontent\x18\x03 \x01(\t\x12\x0c\n\x04\x43ode\x18\x04 \x01(\x05\x12\x10\n\x08\x43omments\x18\x05 \x01(\t\x12,\n\tHeartBeat\x18\x07 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\'\n\x04\x42ody\x18\x08 \x03(\x0b\x32\x19.Message.UserRecordStruct\x1a\xa3\x01\n\rLicenceStruct\x12\x0f\n\x07\x43ompany\x18\x01 \x01(\t\x12\x0f\n\x07Product\x18\x02 \x01(\t\x12\x10\n\x08\x43ustomer\x18\x03 \x01(\t\x12\x0b\n\x03Ref\x18\x04 \x01(\t\x12\x10\n\x08Reseller\x18\x05 \x01(\t\x12(\n\x04\x44\x61te\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rNumberOfSeats\x18\x07 \x01(\x05\x1a\x61\n\x10UserRecordStruct\x12\x0c\n\x04User\x18\x01 \x01(\t\x12\x0c\n\x04Host\x18\x02 \x01(\t\x12\n\n\x02IP\x18\x03 \x01(\t\x12\x11\n\tLogonTime\x18\x05 \x01(\t\x12\x12\n\nUpdateTime\x18\x06 \x01(\t\"\xd1\x01\n\nTypeStruct\x12\t\n\x05Reply\x10\x00\x12\x0c\n\x08TakeSeat\x10\x01\x12\x0f\n\x0bReleaseSeat\x10\x02\x12\x0f\n\x0bRefreshSeat\x10\x03\x12\x14\n\x10QueryConnections\x10\x04\x12\x11\n\rNumberOfSeats\x10\x05\x12\x11\n\rServerVersion\x10\x06\x12\x11\n\rQueryProducts\x10\x07\x12\x10\n\x0cQueryLicence\x10\x08\x12\x14\n\x10WebServerAddress\x10\t\x12\x11\n\x04Kill\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])



_MESSAGE_TYPESTRUCT = _descriptor.EnumDescriptor(
  name='TypeStruct',
  full_name='Message.TypeStruct',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Reply', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TakeSeat', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ReleaseSeat', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RefreshSeat', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QueryConnections', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NumberOfSeats', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ServerVersion', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QueryProducts', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QueryLicence', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WebServerAddress', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Kill', index=10, number=-1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=572,
  serialized_end=781,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_TYPESTRUCT)


_MESSAGE_LICENCESTRUCT = _descriptor.Descriptor(
  name='LicenceStruct',
  full_name='Message.LicenceStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Company', full_name='Message.LicenceStruct.Company', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Product', full_name='Message.LicenceStruct.Product', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Customer', full_name='Message.LicenceStruct.Customer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Ref', full_name='Message.LicenceStruct.Ref', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Reseller', full_name='Message.LicenceStruct.Reseller', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Date', full_name='Message.LicenceStruct.Date', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NumberOfSeats', full_name='Message.LicenceStruct.NumberOfSeats', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=470,
)

_MESSAGE_USERRECORDSTRUCT = _descriptor.Descriptor(
  name='UserRecordStruct',
  full_name='Message.UserRecordStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='User', full_name='Message.UserRecordStruct.User', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Host', full_name='Message.UserRecordStruct.Host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IP', full_name='Message.UserRecordStruct.IP', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LogonTime', full_name='Message.UserRecordStruct.LogonTime', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UpdateTime', full_name='Message.UserRecordStruct.UpdateTime', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=569,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Licence', full_name='Message.Licence', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Type', full_name='Message.Type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='Message.Content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Code', full_name='Message.Code', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Comments', full_name='Message.Comments', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HeartBeat', full_name='Message.HeartBeat', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Body', full_name='Message.Body', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_LICENCESTRUCT, _MESSAGE_USERRECORDSTRUCT, ],
  enum_types=[
    _MESSAGE_TYPESTRUCT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=781,
)

_MESSAGE_LICENCESTRUCT.fields_by_name['Date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_MESSAGE_LICENCESTRUCT.containing_type = _MESSAGE
_MESSAGE_USERRECORDSTRUCT.containing_type = _MESSAGE
_MESSAGE.fields_by_name['Licence'].message_type = _MESSAGE_LICENCESTRUCT
_MESSAGE.fields_by_name['Type'].enum_type = _MESSAGE_TYPESTRUCT
_MESSAGE.fields_by_name['HeartBeat'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_MESSAGE.fields_by_name['Body'].message_type = _MESSAGE_USERRECORDSTRUCT
_MESSAGE_TYPESTRUCT.containing_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {

  'LicenceStruct' : _reflection.GeneratedProtocolMessageType('LicenceStruct', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGE_LICENCESTRUCT,
    '__module__' : 'clsMessage'
    # @@protoc_insertion_point(class_scope:Message.LicenceStruct)
    })
  ,

  'UserRecordStruct' : _reflection.GeneratedProtocolMessageType('UserRecordStruct', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGE_USERRECORDSTRUCT,
    '__module__' : 'clsMessage'
    # @@protoc_insertion_point(class_scope:Message.UserRecordStruct)
    })
  ,
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'clsMessage'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.LicenceStruct)
_sym_db.RegisterMessage(Message.UserRecordStruct)


# @@protoc_insertion_point(module_scope)
